version: "3.8"

services:
  db:
    image: postgres:15
    container_name: threads_db
    environment:
      POSTGRES_DB: threads
      POSTGRES_USER: threadsuser
      POSTGRES_PASSWORD: threadspass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/threads
      SPRING_DATASOURCE_USERNAME: threadsuser
      SPRING_DATASOURCE_PASSWORD: threadspass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  pgdata:
